feat: add bid tables with triggers, functions, and indexes
safetrustcr/Backend pull request #41
Opened 2024-11-29 16:07 UTC by juandiegocv27

❗ ##**PR Information**
Create tables for apartment bid requests and status history tracking to manage the complete lifecycle of tenant apartment bids.

## 🌀 Summary of Changes
- **Database Tables**:
  - `bid_requests`: Stores apartment_id, tenant_id, current_status, proposed_price, desired_move_in, timestamps
  - `bid_status_histories`: Records bid_request_id, status, notes, changed_by, created_at
- **Functions & Triggers**:
  - Auto-update `updated_at` column
  - Record status changes in history table
  - Prevent multiple active bids per tenant
- **Optimizations**:
  - Added indexes on both tables
  - Implemented status constraints and foreign keys

## 🛠 Testing
- working in it...

## 📂 Related Issue
- This pull request will **close #21** upon merging.

2024-11-30 02:31 UTC, rvalenciano commented on migrations/safetrust/1732865994413_create_bid_tables/up.sql
> +CREATE TABLE bid_requests (
Lets add these tables all in:

/metadata/databases/safetrust/tables/tables.yaml

files so they can be tracked in the graphql endpoints.

https://hasura.io/docs/2.0/migrations-metadata-seeds/manage-migrations/#create-manual-migrations

> The corresponding Hasura Metadata changes, if any, can be made directly in the appropriate Metadata file in the /metadata directory, refer to [Metadata format](https://hasura.io/docs/2.0/migrations-metadata-seeds/manage-migrations/).

Check other tables (users) as a reference

2024-11-30 02:32 UTC, rvalenciano requested changes
Lets modify the metadata and we are done

2024-11-30 02:38 UTC, rvalenciano commented on migrations/safetrust/1732865994413_create_bid_tables/up.sql
> +-- Función para registrar cambios de estado
This needs to either be removed or translated to English

2024-11-30 02:38 UTC, rvalenciano commented on migrations/safetrust/1732865994413_create_bid_tables/up.sql
> +-- Trigger para registrar cambios de estado
Same as before

2024-11-30 02:38 UTC, rvalenciano commented on migrations/safetrust/1732865994413_create_bid_tables/up.sql
> +-- Índices para optimización
Same as before

2024-11-30 02:38 UTC, rvalenciano commented on migrations/safetrust/1732865994413_create_bid_tables/up.sql
> +-- Trigger para verificar ofertas activas
Same as before

2024-11-30 02:38 UTC, rvalenciano commented on migrations/safetrust/1732865994413_create_bid_tables/up.sql
> +-- Función para verificar ofertas activas
Same as before

2024-12-04 11:50 UTC, juandiegocv27 reviewed
already made the changes requested

2024-12-05 04:43 UTC, rvalenciano approved these changes

2024-12-05 04:43 UTC, merged