Setting up Karate Test for GraphQl
safetrustcr/Backend pull request #42
Opened 2024-12-02 10:28 UTC by olisaagbafor

# Pull Request for SafeTrust - Add Automated API Testing Framework

❗ **Pull Request Information**

This PR implements comprehensive automated testing for the SafeTrust GraphQL API using the Karate framework. It establishes a robust testing infrastructure focusing on user authentication, permissions, and wallet functionality.

## 🌀 Summary of Changes

- **Test Infrastructure Setup**:
  - Added Karate testing framework configuration
  - Created Docker test environment
  - Implemented test reporting system

- **Test Suite Implementation**:
  - Authentication tests (Firebase token validation, JWT claims)
  - User management tests (CRUD operations, permissions)
  - Wallet functionality tests (creation, validation)
  - Error scenario coverage

- **Project Structure**:
  - Organized test files in feature-based hierarchy
  - Added reusable test helpers and schemas
  - Implemented environment-specific configurations

## 🛠 Testing

### Evidence Before Solution

- No automated testing infrastructure
- Manual verification required for API changes
- Inconsistent test coverage

### Evidence After Solution

- Automated test execution via Docker
- Comprehensive test coverage for:
  - User authentication flows
  - RBAC permissions
  - Wallet operations
  - Error scenarios
- Generated test reports showing coverage metrics

## 📂 Related Issue

This pull request will **close #29** - Implement automated API testing infrastructure

---

🎉 Thank you for reviewing this PR!

2024-12-03 00:24 UTC, diegoTech14 commented
Hi @olisaagbafor 

1. Could you change the dependencies from package.json in the tests directory to the main package.json?
2. We would like to see the setup working in a video. Could you make us a video, please?

For the video you can use loom -> https://www.loom.com/looms/videos

2024-12-03 20:25 UTC, diegoTech14 commented
@olisaagbafor Hey man, PR looks good, just would like to see a video please 🚀

2024-12-03 20:26 UTC, diegoTech14 approved these changes

2024-12-03 21:20 UTC, olisaagbafor commented
@diegoTech14 The video link is [here](https://www.loom.com/share/78c1130e709747ce8f02bc6004a9c358?sid=e0d43388-43e3-40eb-90d3-e9a169a0ea60)

2024-12-03 21:50 UTC, diegoTech14 commented
> @diegoTech14 The video link is [here](https://www.loom.com/share/78c1130e709747ce8f02bc6004a9c358?sid=e0d43388-43e3-40eb-90d3-e9a169a0ea60)

Will check ASAP, thanks!

2024-12-03 23:42 UTC, rvalenciano commented on tests/docker-compose.test.yml
> +  postgres:
This looks great, however lets move this to the root folder as well, also lets rename it as `docker-compose-test.yml`

2024-12-03 23:43 UTC, rvalenciano commented on tests/docker-compose.test.yml
> +  graphql-engine:
Lets rename this to `graphql-engine-test`

2024-12-03 23:44 UTC, rvalenciano commented on tests/docker-compose.test.yml
> +  postgres:
Lets also rename this to `postgres_test`

2024-12-03 23:45 UTC, rvalenciano commented on tests/src/test/java/karate/TestRunner.java
> +package karate;
Lets avoid using Java for this, can we set this up with NodeJS?

2024-12-03 23:45 UTC, rvalenciano requested changes
@olisaagbafor this is looking great, some mino comments;

Also, can we add some instructions on the README on how to run the tests?

Best

2024-12-05 16:51 UTC, diegoTech14 commented
@olisaagbafor Hey man, any updates?

2024-12-05 18:53 UTC, olisaagbafor commented
Yeah, am on it, Just had some buds to clear up...

2024-12-06 19:19 UTC, sotoJ24 approved these changes

2024-12-08 01:31 UTC, zleypner commented
Hello @olisaagbafor , 
May please have your Telegram or contact me at https://t.me/anwar_zlcr ?
I am having an error while running the Karate Tests.

2024-12-11 00:27 UTC, zleypner commented
Hello @olisaagbafor! As per our conversation in telegram. Do you have any updates regarding the errors for the tests?

2024-12-11 00:28 UTC, olisaagbafor commented
@zleypner Yeah I do will update soon

2024-12-11 03:48 UTC, olisaagbafor commented
@zleypner the errors should be gone now, and I have updated the README for the instruction on how to run the test

2024-12-11 03:49 UTC, olisaagbafor commented
Please let me know if there is anything else...

2024-12-11 21:39 UTC, zleypner commented
@olisaagbafor Thank you for the updates! Checking

2024-12-11 23:50 UTC, zleypner commented
Hello @olisaagbafor!
 After running Im getting this command:
docker compose -f docker-compose-test.yml up --build --abort-on-container-exit
I am getting this error
Attaching to graphql-engine-test-1, karate-1, postgres_test-1
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: driver failed programming external connectivity on endpoint backend-postgres_test-1 (70ebc50c36c63af19d5d1241effdb232e5b3552201e6aa805e5f94496d856768): Bind for 0.0.0.0:5432 failed: port is already allocated

2024-12-12 02:45 UTC, zleypner commented
We are almost there @olisaagbafor , thank you! Would yo be so kind to please update the Loom video?

2024-12-12 03:03 UTC, olisaagbafor commented
Ok will do that shortly @zleypner

2024-12-12 04:33 UTC, olisaagbafor commented
@zleypner the video link is [here](https://www.loom.com/share/0584af1616404c80b2e0bf2f6feef270?sid=03bf9bc3-05c2-4d2a-8c41-cc0c6cd5bc50)

2024-12-12 07:07 UTC, zleypner commented
Thanks @olisaagbafor for this outstanding work! The implementation of the Karate testing framework is extremely well-structured and thorough. I particularly appreciate:

Your responsiveness to feedback and willingness to iterate on improvements
The clear documentation and testing instructions you've added to the README
Your professional approach to addressing all review comments and technical issues

Your attention to detail and commitment to quality really shows through in this PR. This testing infrastructure will be invaluable for maintaining code quality as we scale. Great job on delivering such a robust solution! 🎯 👏

2024-12-12 07:39 UTC, olisaagbafor commented
@zleypner thanks alot for your complements ❤️, I truly appreciate 🙏

2024-12-12 08:07 UTC, zleypner commented
@olisaagbafor There is one detail pending mentioned in the Contributors guideline. Please update the atomic commits based on the git guidelines. 
![image](https://github.com/user-attachments/assets/aa348a5b-4491-4534-9b68-af22ade249b3)
![image](https://github.com/user-attachments/assets/bfab51ee-1711-4d8b-a798-5d2c5ce85166)

https://github.com/safetrustcr/Frontend/issues/35

2024-12-12 22:31 UTC, closed without merging