feat: added seed file for bid_status_histories
safetrustcr/Backend pull request #61
Opened 2024-12-17 15:44 UTC by ikezuby2012

# Pull Request for SafeTrust - Close Issue

❗ **Pull Request Information**

feat: added seed file for bid_status_histories table at seeds/safetrust folder
Add here some information

## 🌀 Summary of Changes

- **Add here the changes**:
- Changes just made to seeds/safetrust (new features)
- **More changes**:

## 🛠 Testing
NOT NEEDED!
### Evidence Before Solution

- **Video**: [Link to Loom video](https://loom.com)

### Evidence After Solution

- **Video**: [Link to Loom video](https://loom.com)

## 📂 Related Issue

This pull request will **close # [Issue Number]** upon merging.

This Pull request will close #53 upon merging
---

🎉 Thank you for reviewing this PR! 🎉

2024-12-18 03:48 UTC, rvalenciano commented on seeds/safetrust/1734448906685_bid_status_histories.sql
> +    (uuid_generate_v4(), (SELECT id FROM bid_requests LIMIT 1 OFFSET 3), 'In_Progress', 'Work on the bid has commenced.', (SELECT id FROM users WHERE username = 'user'), NOW() - INTERVAL '3 days'),
I would rephrase this as: 

 'Work on the bid has begun.'

2024-12-18 03:49 UTC, rvalenciano commented on storage-service/package.json
> +    "storage-service": "file:",
Why are we touching this? Please undo this change.

2024-12-18 03:49 UTC, rvalenciano commented on package.json
> +    "winston": "^3.17.0"
Please undo these changes.

2024-12-18 07:29 UTC, ikezuby2012 commented on seeds/safetrust/1734448906685_bid_status_histories.sql
> +    (uuid_generate_v4(), (SELECT id FROM bid_requests LIMIT 1 OFFSET 3), 'In_Progress', 'Work on the bid has commenced.', (SELECT id FROM users WHERE username = 'user'), NOW() - INTERVAL '3 days'),
noted

2024-12-18 07:39 UTC, ikezuby2012 commented on package.json
> +    "winston": "^3.17.0"
Done, please review changes

2024-12-18 14:09 UTC, ikezuby2012 commented
Done with the changes

2024-12-19 22:30 UTC, sotoJ24 commented
> Done with the changes

Thank you @ikezuby2012

2024-12-19 22:31 UTC, sotoJ24 approved these changes

2024-12-20 19:07 UTC, sotoJ24 approved these changes

2024-12-21 01:55 UTC, sotoJ24 reviewed
Dear @ikezuby2012, the package-lock.json is still modified, can you please undo that's changes, btw we need almost 20 rows to test the pagination, thanks and regards

![Screenshot 2024-12-20 195034](https://github.com/user-attachments/assets/5bb712d9-c520-4a67-8962-9b3ed11010b2)

2024-12-22 06:57 UTC, sotoJ24 requested changes
please, keep us updated about the request changes

2024-12-22 22:21 UTC, ikezuby2012 commented
done, please review

2024-12-23 21:54 UTC, sotoJ24 approved these changes

2024-12-31 01:20 UTC, sotoJ24 requested changes
Hi Dear @ikezuby2012 hope you're doing well

we noticed that when the query is executed, throwing an error:  ` "message": "column \"username\" does not exist"`

![Screenshot 2024-12-30 191309](https://github.com/user-attachments/assets/729b60a4-6519-44c2-a87a-8924e29c2110)

The username column must be replaced with the **email** column for it to work.

Whatever you need just let Us know, thanks

2024-12-31 14:56 UTC, ikezuby2012 commented
Please review

2024-12-31 22:29 UTC, sotoJ24 commented
Hi @ikezuby2012, it still doesn't work, because the email table does not exist
![Screenshot 2024-12-31 160553](https://github.com/user-attachments/assets/8595460e-ac5d-4a3d-91e1-f1488b6dd2e6)

could you make the query something like this: 

> `INSERT INTO bid_status_histories (id, bid_request_id, status, notes, changed_by, created_at) VALUES (uuid_generate_v4(), (SELECT id FROM bid_requests LIMIT 1 OFFSET 0), 'Submitted', 'Bid request has been submitted.', (SELECT id FROM users LIMIT 1 OFFSET 0), NOW()),`  

 and the following,
 Regards

2024-12-31 22:35 UTC, sotoJ24 requested changes
Hi @ikezuby2012, it still doesn't work, because the email table does not exist
![Screenshot 2024-12-31 160553](https://github.com/user-attachments/assets/8595460e-ac5d-4a3d-91e1-f1488b6dd2e6)

could you make the query something like this: 

> `INSERT INTO bid_status_histories (id, bid_request_id, status, notes, changed_by, created_at) VALUES (uuid_generate_v4(), (SELECT id FROM bid_requests LIMIT 1 OFFSET 0), 'Submitted', 'Bid request has been submitted.', (SELECT id FROM users LIMIT 1 OFFSET 0), NOW()),`  

 and the following,
 Regards

2025-01-01 01:28 UTC, ikezuby2012 commented
check now

2025-01-02 20:05 UTC, sotoJ24 approved these changes

2025-01-08 00:30 UTC, sotoJ24 requested changes
![Screenshot 2025-01-07 182341](https://github.com/user-attachments/assets/da8ffdae-b5ed-465d-b697-df5d79de5a94)
![Screenshot 2025-01-07 182312](https://github.com/user-attachments/assets/83305f0c-5027-49dc-8e59-8b3ad49d63f9)

Hi,

Dear @ikezuby2012  could you please help us to remove those package dependencies from the package-lock.json, please

2025-01-08 14:08 UTC, ikezuby2012 commented
check again

2025-01-08 21:31 UTC, sotoJ24 requested changes

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +        "cucumber-html-reporter": "^5.5.0",
Would you remove it `"cucumber-html-reporter": "^5.5.0",` and the following

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/ansi-styles": {
**Remove** -> 

```
"node_modules/ansi-styles": {
      "version": "3.2.1",
      "resolved": "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz",
      "integrity": "sha512-VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==",
      "dependencies": {
        "color-convert": "^1.9.0"
      },
      "engines": {
        "node": ">=4"
      }
    }, 
```

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/chalk": {
Remove -> 

`
"node_modules/chalk": {
      "version": "2.4.2",
      "resolved": "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz",
      "integrity": "sha512-Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==",
      "dependencies": {
        "ansi-styles": "^3.2.1",
        "escape-string-regexp": "^1.0.5",
        "supports-color": "^5.3.0"
      },
      "engines": {
        "node": ">=4"
      }
    },
`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/cucumber-html-reporter": {
Remove  ->   
 ` 
 "node_modules/cucumber-html-reporter": {
      "version": "5.5.1",
      "resolved": "https://registry.npmjs.org/cucumber-html-reporter/-/cucumber-html-reporter-5.5.1.tgz",
      "integrity": "sha512-bXy8aUSUhgFavsB9T4nQLx4B3Q+HBY2Chwqs6bOMOgLKqWSx2VBYjEgzv57TvQvEbrluAiEqP93rDBLimTodnQ==",
      "dependencies": {
        "chalk": "^2.4.2",
        "find": "^0.3.0",
        "fs-extra": "^8.1.0",
        "js-base64": "^2.3.2",
        "jsonfile": "^5.0.0",
        "lodash": "^4.17.11",
        "node-emoji": "^1.10.0",
        "open": "^6.4.0",
        "uuid": "^3.3.3"
      }
    },
`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/escape-string-regexp": {
Remove -> ` 
 "node_modules/escape-string-regexp": {
      "version": "1.0.5",
      "resolved": "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz",
      "integrity": "sha512-vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==",
      "engines": {
        "node": ">=0.8.0"
      }
    },
`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/find": {
Remove -> 

`
 "node_modules/find": {
      "version": "0.3.0",
      "resolved": "https://registry.npmjs.org/find/-/find-0.3.0.tgz",
      "integrity": "sha512-iSd+O4OEYV/I36Zl8MdYJO0xD82wH528SaCieTVHhclgiYNe9y+yPKSwK+A7/WsmHL1EZ+pYUJBXWTL5qofksw==",
      "dependencies": {
        "traverse-chain": "~0.1.0"
      }
    },
`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/fs-extra": {
Remove -> 

`
"node_modules/fs-extra": {
      "version": "8.1.0",
      "resolved": "https://registry.npmjs.org/fs-extra/-/fs-extra-8.1.0.tgz",
      "integrity": "sha512-yhlQgA6mnOJUKOsRUFsgJdQCvkKhcz8tlZG5HBQfReYZy46OwLcY+Zia0mtdHsOo9y/hP+CxMN0TU9QxoOtG4g==",
      "dependencies": {
        "graceful-fs": "^4.2.0",
        "jsonfile": "^4.0.0",
        "universalify": "^0.1.0"
      },
      "engines": {
        "node": ">=6 <7 || >=8"
      }
    },
    "node_modules/fs-extra/node_modules/jsonfile": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/jsonfile/-/jsonfile-4.0.0.tgz",
      "integrity": "sha512-m6F1R3z8jjlf2imQHS2Qez5sjKWQzbuuhuJ/FKYFRZvPE3PuHcSMVZzfsLhGVOkfd20obL5SWEBew5ShlquNxg==",
      "optionalDependencies": {
        "graceful-fs": "^4.1.6"
      }
    },
`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/graceful-fs": {
Remove -> 

`    
"node_modules/graceful-fs": {
      "version": "4.2.11",
      "resolved": "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz",
      "integrity": "sha512-RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ=="
    },
`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/has-flag": {
Remove -> 
`   "node_modules/has-flag": {
      "version": "3.0.0",
      "resolved": "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz",
      "integrity": "sha512-sKJf1+ceQBr4SMkvQnBDNDtf4TXpVhVGateu0t918bl30FnbE2m4vNLX+VWe/dpjlb+HugGYzW7uQXH98HPEYw==",
      "engines": {
        "node": ">=4"
      }
    },
`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/is-wsl": {
Remove -> 

` "node_modules/is-wsl": {
      "version": "1.1.0",
      "resolved": "https://registry.npmjs.org/is-wsl/-/is-wsl-1.1.0.tgz",
      "integrity": "sha512-gfygJYZ2gLTDlmbWMI0CE2MwnFzSN/2SZfkMlItC4K/JBlsWVDB0bO6XhqcY13YXE7iMcAJnzTCJjPiTeJJ0Mw==",
      "engines": {
        "node": ">=4"
      }
    },
    "node_modules/js-base64": {
      "version": "2.6.4",
      "resolved": "https://registry.npmjs.org/js-base64/-/js-base64-2.6.4.tgz",
      "integrity": "sha512-pZe//GGmwJndub7ZghVHz7vjb2LgC1m8B07Au3eYqeqv9emhESByMXxaEgkUkEqJe87oBbSniGYoQNIBklc7IQ=="
    },
    "node_modules/jsonfile": {
      "version": "5.0.0",
      "resolved": "https://registry.npmjs.org/jsonfile/-/jsonfile-5.0.0.tgz",
      "integrity": "sha512-NQRZ5CRo74MhMMC3/3r5g2k4fjodJ/wh8MxjFbCViWKFjxrnudWSY5vomh+23ZaXzAS7J3fBZIR2dV6WbmfM0w==",
      "dependencies": {
        "universalify": "^0.1.2"
      },
      "optionalDependencies": {
        "graceful-fs": "^4.1.6"
      }
    },
`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/lodash": {
Remove ->

`    "node_modules/lodash": {
      "version": "4.17.21",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz",
      "integrity": "sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg=="
    },`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/node-emoji": {
Remove -> 
`    "node_modules/node-emoji": {
      "version": "1.11.0",
      "resolved": "https://registry.npmjs.org/node-emoji/-/node-emoji-1.11.0.tgz",
      "integrity": "sha512-wo2DpQkQp7Sjm2A0cq+sN7EHKO6Sl0ctXeBdFZrL9T9+UywORbufTcTZxom8YqpLQt/FqNMUkOpkZrJVYSKD3A==",
      "dependencies": {
        "lodash": "^4.17.21"
      }
    },`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/open": {
Remove ->

`    "node_modules/open": {
      "version": "6.4.0",
      "resolved": "https://registry.npmjs.org/open/-/open-6.4.0.tgz",
      "integrity": "sha512-IFenVPgF70fSm1keSd2iDBIDIBZkroLeuffXq+wKTzTJlBpesFWojV9lb8mzOfaAzM1sr7HQHuO0vtV0zYekGg==",
      "dependencies": {
        "is-wsl": "^1.1.0"
      },
      "engines": {
        "node": ">=8"
      }
    },`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/supports-color": {
Remove ->

`    "node_modules/supports-color": {
      "version": "5.5.0",
      "resolved": "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz",
      "integrity": "sha512-QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==",
      "dependencies": {
        "has-flag": "^3.0.0"
      },
      "engines": {
        "node": ">=4"
      }
    },`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/traverse-chain": {
Remove ->

`    "node_modules/traverse-chain": {
      "version": "0.1.0",
      "resolved": "https://registry.npmjs.org/traverse-chain/-/traverse-chain-0.1.0.tgz",
      "integrity": "sha512-up6Yvai4PYKhpNp5PkYtx50m3KbwQrqDwbuZP/ItyL64YEWHAvH6Md83LFLV/GRSk/BoUVwwgUzX6SOQSbsfAg=="
    },`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/universalify": {
Remove ->
`   "node_modules/universalify": {
      "version": "0.1.2",
      "resolved": "https://registry.npmjs.org/universalify/-/universalify-0.1.2.tgz",
      "integrity": "sha512-rBJeI5CXAlmy1pV+617WB9J63U6XcazHHF2f2dbJix4XzpUF0RS3Zbj0FGIOCAva5P/d/GBOYaACQ1w+0azUkg==",
      "engines": {
        "node": ">= 4.0.0"
      }
    },
`

2025-01-08 21:31 UTC, sotoJ24 commented on package-lock.json
> +    "node_modules/uuid": {
Remove -> 

`    "node_modules/uuid": {
      "version": "3.4.0",
      "resolved": "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz",
      "integrity": "sha512-HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==",
      "deprecated": "Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.",
      "bin": {
        "uuid": "bin/uuid"
      }
    },`

2025-01-20 05:51 UTC, closed without merging